table Food {
  id integer [pk]
  name varchar
  description varchar
  category varchar
  price float
  restaurant varchar [ref: > Restaurant.id]
}

table Restaurant {
  id integer [pk]
  name varchar
  description varchar
  rate float
  cnpj long
  phone long
  location integer [ref: > Location.id]
  user varchar [ref: - User.id]
}

table User {
  id integer [pk]
  name varchar
  email varchar
  password varchar
  role integer
  location integer [ref: < Location.id]
}

table Location {
  id integer [pk]
  number integer
  street varchar
  neighborhood varchar
  complement varchar
}

table Order {
  id integer [pk]
  created_at timestamp
  rate float
  user varchar [ref: > User.id]
  restaurant varchar [ref: > Restaurant.id]
  location integer [ref: > Location.id]
}

table OrderItem {
  quantity integer 
  food integer [pk, ref: > Food.id]
  order integer [pk, ref: > Order.id]
}
