table foods {
  id serial [pk]
  name varchar
  description varchar
  category varchar
  price float
  restaurant_id varchar [ref: > restaurants.id]
}

table restaurants {
  id serial [pk]
  name varchar
  description varchar
  rate float
  cnpj varchar
  phone varchar
  location_id integer [ref: > locations.id]
  user_id integer [ref: > users.id]
}

table users {
  id serial [pk]
  name varchar
  email varchar
  password varchar
  role integer
  location_id integer [ref: < locations.id]
}

table locations {
  id serial [pk]
  number integer
  street varchar
  neighborhood varchar
  complement varchar
}

table orders {
  id serial [pk]
  created_at timestamp
  rate float
  user_id integer [ref: > users.id]
  restaurant_id integer [ref: > restaurants.id]
  location_id integer [ref: > locations.id]
}

table order_items {
  quantity integer 
  food_id integer [pk, ref: > foods.id]
  order_id integer [pk, ref: > orders.id]
}
